name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test the Flask server
      id: test-the-flask-server
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 45
        setup-command: pip install flask
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-THE-FLASK-SERVER_RESULTS: "${{steps.test-the-flask-server.outputs.result}}"
      with:
        runners: test-the-flask-server
